<?php
/**
 * @package Admin Add Customer
 * @subpackage plugins
 * @copyright Copyright 2003-2026 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://zen-cart.com GNU Public License V2.0
 * @version $Id: add_customers.php 2026-08-26 15:49:10Z dbltoe $
 */
require 'includes/application_top.php';

require DIR_WS_CLASSES . 'currencies.php';
$currencies = new currencies();

$error = false;
$errors = [];
$processed = false;

require DIR_WS_CLASSES . 'addCustomers.php';
$acfa = new addCustomers();

// -----
// Plain GET-triggered downloads/printouts (a clicked link, not a form submission), handled
// immediately and independently of the $_POST action-switch below, bypassing the normal admin
// page chrome entirely.
//
$downloadAction = (isset($_GET['action'])) ? $_GET['action'] : false;
if ($downloadAction === 'download_csv_template') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="add_customers_template.csv"');
    echo $acfa->getCsvTemplateContents();
    exit();
}
$printFormMissingFile = '';
if ($downloadAction === 'print_form') {
    // -----
    // These are static PDFs the store owner supplies (not generated by this plugin - Zen
    // Cart core ships no PDF-generation library), placed at the plugin's own root, a sibling
    // of this admin/ folder.
    //
    $wantsWholesaleForm = ($acfa->wholesaleEnabled() && isset($_GET['wholesale']) && $_GET['wholesale'] === '1');
    $pdfFilename = ($wantsWholesaleForm) ? 'signup_form_wholesale.pdf' : 'signup_form.pdf';
    $pdfPath = dirname(__DIR__) . '/pdf/' . $pdfFilename;
    if (is_file($pdfPath)) {
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="' . $pdfFilename . '"');
        header('Content-Length: ' . filesize($pdfPath));
        readfile($pdfPath);
        exit();
    }
    // -----
    // File not supplied yet - fall through to the normal page render with an on-page notice
    // instead of a broken download.
    //
    $printFormMissingFile = $pdfFilename;
}

// -----
// Initialize $cInfo array for single-entry form.
//
$default_customer = [
    'customers_firstname' => '',
    'customers_lastname' => '',
    'customers_email_address' => '',
    'customers_telephone' => '',
    'customers_group_pricing' => '0',
    'customers_whole' => '0',
    'customers_tax_number' => '',
];
$cInfo = new objectInfo($default_customer);
unset($default_customer);

// -----
// Determine what to do next, based on the posted 'action'.
//
$action = (isset($_POST['action'])) ? $_POST['action'] : false;
if ($action !== false) {
    switch ($action) {
        // -----
        // Adding a single-customer via the associated form.  The input is validated and,
        // if found to be OK, subsequently written to the database.
        //
        case 'add_single':
            list($cInfo, $errors) = $acfa->validateCustomer($_POST);
            if (count($errors) === 0) {
                $customerName = $acfa->insertCustomer($_POST);
                $messageStack->add_session(sprintf(MESSAGE_CUSTOMER_OK, htmlspecialchars($customerName, ENT_QUOTES, CHARSET)), 'success');
                zen_redirect(zen_href_link(FILENAME_ADD_CUSTOMERS));
            }
            break;

        // -----
        // Adding multiple customers, via an uploaded .csv/.txt file.
        //
        case 'add_multiple':
            $errors = $acfa->checkFileUpload();
            if (count($errors) === 0) {
                $messageStack->add_session(sprintf(MESSAGE_CUSTOMERS_OK, $acfa->getCustomersInserted()), 'success');
                zen_redirect(zen_href_link(FILENAME_ADD_CUSTOMERS));
            }
            break;

        // -----
        // Uploading (or replacing) the welcome email's optional header banner image - see
        // addCustomers::uploadEmailHeaderImage().
        //
        case 'upload_email_header':
            $errors = $acfa->uploadEmailHeaderImage();
            if (count($errors) === 0) {
                $messageStack->add_session(MESSAGE_EMAIL_HEADER_UPLOADED, 'success');
                zen_redirect(zen_href_link(FILENAME_ADD_CUSTOMERS));
            }
            break;

        // -----
        // Resending the customer's welcome/activation email, optionally resetting their
        // password. Also regenerates their activation token.
        //
        case 'resend_email':
            if (!isset($_POST['resend_id']) || (int)$_POST['resend_id'] === 0) {
                $errors[] = ERROR_NO_CUSTOMER_SELECTED;
            } else {
                $custInfo = $db->Execute(
                    "SELECT customers_firstname, customers_lastname, customers_email_address
                       FROM " . TABLE_CUSTOMERS . "
                      WHERE customers_id = " . (int)$_POST['resend_id'] . "
                      LIMIT 1"
                );
                if ($custInfo->EOF) {
                    $errors[] = ERROR_NO_CUSTOMER_SELECTED;
                } else {
                    $acfa->regenerateAndResendToken((int)$_POST['resend_id'], isset($_POST['reset_pw']) && $_POST['reset_pw'] === '1');
                    // -----
                    // Escaped rather than trusted. insertCustomer() runs names through core's
                    // zen_sanitize_string(), but this dropdown is fed by createCustomerDropdown(),
                    // which selects EVERY customer with customers_authorization != AUTH_OK -- not
                    // only the ones this plugin created. A customer registered through the
                    // storefront on an approval-required store, or edited in core's own admin,
                    // reaches this line too, and nothing here can vouch for what is in their name.
                    // messageStack output is echoed as raw HTML, so it is escaped at the point of
                    // use instead of reasoned about.
                    //
                    $messageStack->add_session(
                        CUSTOMER_EMAIL_RESENT . ' '
                        . htmlspecialchars(
                            $custInfo->fields['customers_firstname'] . ' ' . $custInfo->fields['customers_lastname']
                            . ' (' . $custInfo->fields['customers_email_address'] . ')',
                            ENT_QUOTES,
                            CHARSET
                        ),
                        'success'
                    );
                    zen_redirect(zen_href_link(FILENAME_ADD_CUSTOMERS));
                }
            }
            break;

        // -----
        // Permanently deletes customers who signed up before the chosen date and never got as
        // far as having a complete address on file - see addCustomers::deleteAbandonedSignups().
        //
        case 'delete_abandoned':
            $delete_before_date = (isset($_POST['delete_before_date'])) ? trim($_POST['delete_before_date']) : '';
            $deletedCount = $acfa->deleteAbandonedSignups($delete_before_date);
            if ($deletedCount === false) {
                $errors[] = ERROR_INVALID_DELETE_DATE;
            } else {
                $messageStack->add_session(sprintf(MESSAGE_ABANDONED_DELETED, $deletedCount), 'success');
                zen_redirect(zen_href_link(FILENAME_ADD_CUSTOMERS));
            }
            break;

        // -----
        // Anything else, nothing to be done.
        //
        default:
            break;
    }
}
?>
<!doctype html>
<html <?php echo HTML_PARAMS; ?>>
<head>
<?php require DIR_WS_INCLUDES . 'admin_html_head.php'; ?>
<style>
/* -----
   .row.formAreaTitle is core's own admin theme class, not this plugin's. This <style> block
   only ever loads on this one page, so it can't affect .row.formAreaTitle anywhere else in
   the admin regardless of selector scope - no need for extra scoping here. Matching core's
   own two-class selector (rather than just .formAreaTitle) keeps the same specificity, so
   this reliably overrides rather than risking a specificity tie.

   font-size here also replaces core's own font-size: 12px (set on .formAreaTitle) with rem
   instead, so it scales with the user's own browser/OS text-size or zoom preference instead
   of staying fixed regardless of it - more noticeable on mobile/tablet than desktop. 1.2rem
   matches the size core's own stylesheet.css already uses for .control-label elsewhere in
   this admin theme, and reads noticeably easier than the original 12px without crowding
   the page.
*/
.row.formAreaTitle { margin-top: 1.5em; margin-bottom: 0.5em; font-size: 1.2rem; }

/* -----
   Color-contrast fixes (WCAG AA/AAA), per a Siteimprove scan of this page. All three classes
   below are core's own Bootstrap-derived admin theme classes (.help-block, .btn-primary,
   .btn-danger), not this plugin's - overridden here, scoped to this one page the same way as
   .row.formAreaTitle above, rather than touching the shared stylesheet.
     - .help-block was #737373 on white (4.31:1, fails AA's 4.5:1). #525252 clears AAA's 7:1.
     - .btn-primary was white-on-#337AB7. #145b09 clears AAA's 7:1 with white text.
     - .btn-danger was white-on-#D0534F. #AA2420 clears AA/AAA with white text.
   Hover/focus states simply reverse background/text on the same two colors, so the contrast
   ratio is identical in both states.

   .help-block's font-size is added here too, matching .row.formAreaTitle above: core's own
   stylesheet.css already sets .control-label to 1.2rem, so this brings the field help text
   up to read at the same size as the labels it belongs to.

   .control-label itself is included below for the same 1.2rem, even though it's already set
   in core's own stylesheet.css - confirmed via live inspection that it wasn't reliably taking
   effect on this specific page. Scoped here the same way as everything else in this block,
   rather than chasing down why core's own rule wasn't reaching this page.

   input, select, textarea matches core's own generic (element-selector, not class) rule of
   the same name, set at a fixed 11px in the shared stylesheet - most visible in the "Please
   Choose" placeholder text of the Resend the Welcome E-Mail customer dropdown. Same 1.2rem
   as everything else above; matching core's own selector exactly (rather than a class) keeps
   the same specificity, so this reliably overrides rather than risking a specificity tie.
*/
.help-block { color: #525252; font-size: 1.2rem; }
.control-label { font-size: 1.2rem; }
input, select, textarea { font-size: 1.2rem; }
.btn-primary { background-color: #145b09; border-color: #145b09; color: #FFFFFF; }
.btn-primary:hover, .btn-primary:focus { background-color: #FFFFFF; border-color: #145b09; color: #145b09; }
.btn-danger { background-color: #AA2420; border-color: #AA2420; color: #FFFFFF; }
.btn-danger:hover, .btn-danger:focus { background-color: #FFFFFF; border-color: #AA2420; color: #AA2420; }

/* -----
   Required-field asterisk: #A94442 on #F2DEDE background is Bootstrap's stock .alert-danger
   color pair, which is almost certainly what core wraps the "*" in (this plugin doesn't render
   it itself - it comes from core's own required-field markup). #882321 clears 7:1 against that
   same #F2DEDE background. NOTE: inferred from the color match, not from having actually seen
   the rendered markup - if this doesn't visibly take effect, the real selector is something
   other than .alert-danger and I'll need the actual class name to target it correctly.
*/
.alert-danger { color: #882321; }

/* -----
   44x44px minimum touch target (WCAG 2.5.5, AAA) for every button/link styled as a button on
   this page, including the smaller .btn-sm ones (Download CSV Template, Print Sign-Up Form,
   the CSV help icon) - min-height/min-width set a floor without shrinking anything already
   larger, and inline-flex centers the (sometimes short) content within that floor.
*/
.btn { min-height: 44px; min-width: 44px; display: inline-flex; align-items: center; justify-content: center; }

/* -----
   Print Sign-Up Form and Print Sign-Up Form (with Wholesale option) share a row, each in
   its own dedicated column class rather than the shared col-md-6 (which every other
   two-up field on this page still uses). Bootstrap's .btn keeps its default
   white-space: nowrap here - a single unbroken line reads better than a wrapped one - so
   the two columns are unevenly split (35%/65%) to give the longer wholesale label enough
   room to fit on one line without overflowing its box, confirmed against a live
   screenshot at 1600px wide.
*/
@media (min-width: 992px) {
    .col-print-standard { width: 35%; }
    .col-print-wholesale { width: 65%; }
}

/* -----
   The page's own main left/right split (Email Header Image/Bulk Upload/Resend/Delete
   Unclaimed Signups on the left, Single Customer Entry on the right) used Bootstrap's
   plain col-md-4/col-md-8 (33.33%/66.67%), same as .col-md-6 elsewhere on this page -
   editing those directly would affect every other col-md-4/col-md-8 element in the whole
   admin, not just this page. Dedicated classes instead, at 40%/60%: the right-hand
   single-entry fields don't need two-thirds of the page width, and giving some of that
   space back to the left column gives its own fields (particularly the CSV file field)
   more comfortable room.
*/
@media (min-width: 992px) {
    .col-main-left { width: 40%; }
    .col-main-right { width: 60%; }
}
</style>
</head>

<body>
<?php
require DIR_WS_INCLUDES . 'header.php';

$infoDivContents = '';
if (count($errors) > 0) {
    // -----
    // Every value interpolated into this HTML is escaped at this output boundary, not wherever
    // it originated - some error messages built in addCustomers.php's validateCustomer()/
    // checkFileUpload() carry a submitted value verbatim (e.g. an invalid email address, or a
    // first/last name that only went through zen_db_prepare_input(), not the <>-stripping
    // zen_sanitize_string() insertCustomer() applies at actual insert time), and the uploaded
    // file's own name below is entirely attacker/admin-controlled. Escaping here rather than at
    // each origin covers every current and future message the same way, regardless of what it
    // happens to contain.
    //
    $infoDivContents = '<div class="errorDiv" role="alert"><p class="errorBold">' . ERROR_CUSTOMER_ERROR_1 . (($action === 'add_multiple' && !empty($_FILES['bulk_upload']['name'])) ? (' (' . htmlspecialchars($_FILES['bulk_upload']['name'], ENT_QUOTES, CHARSET) . ')') : '') . ':' . '</p><ul>';

    foreach ($errors as $line_no => $error) {
        if (is_array($error)) {
            $infoDivContents .= '<div class="error">' . sprintf(ERROR_ON_LINE, $line_no) . '</div><ul>';
            foreach ($error as $err) {
                $infoDivContents .= '<li class="error">' . htmlspecialchars($err, ENT_QUOTES, CHARSET) . '</li>';
            }
            $infoDivContents .= '</ul>';
        } else {
            $infoDivContents .= '<li class="error">' . htmlspecialchars($error, ENT_QUOTES, CHARSET) . '</li>';
        }
    }
    $infoDivContents .= '</ul></div>';
}

$resendID = (isset($_POST['resend_id'])) ? $_POST['resend_id'] : 0;
$wholesaleEnabled = $acfa->wholesaleEnabled();
?>
    <div class="container-fluid" role="main">
        <h1><?php echo HEADING_TITLE; ?></h1>
        <div class="col-md-4 col-main-left">
<?php
// -----
// Email-header-image upload form rendering. Placed above Bulk Upload deliberately - the
// header image (if used) should be set before a bulk upload that's about to trigger a lot of
// welcome emails, not after.
//
if ($action == 'upload_email_header') {
    echo $infoDivContents;
}
$currentHeaderImageUrl = $acfa->getHeaderImageUrl();
?>
            <?php echo zen_draw_form('email_header', FILENAME_ADD_CUSTOMERS, '', 'post', 'enctype="multipart/form-data" class="form-horizontal"') .
                  zen_hide_session_id() .
                  zen_draw_hidden_field('action', 'upload_email_header'); ?>
            <h2 class="row formAreaTitle"><?php echo EMAIL_HEADER_IMAGE_TITLE; ?></h2>
            <div class="formArea">
                <p class="help-block"><?php echo HELPTEXT_EMAIL_HEADER_IMAGE; ?></p>
<?php
if ($currentHeaderImageUrl !== '') {
?>
                <p class="help-block"><?php echo TEXT_CURRENT_HEADER_IMAGE; ?><br><img src="<?php echo $currentHeaderImageUrl; ?>" style="max-width:300px;height:auto;" alt="<?php echo ALT_CURRENT_HEADER_IMAGE; ?>" /></p>
<?php
}
?>
                <div class="form-group">
                    <?php echo zen_draw_label(TEXT_EMAIL_HEADER_IMPORT, 'email_header_image', 'class="col-sm-4 control-label"'); ?>
                    <div class="col-sm-8 col-md-6"><?php echo zen_draw_file_field('email_header_image', false, 'class="form-control" id="email_header_image"'); ?></div>
                </div>
                <div class="row text-right">
                    <button name="upload_email_header_btn" type="submit" class="btn btn-primary"><?php echo IMAGE_UPLOAD; ?></button>
                </div>
            </div>
            <?php echo '</form>'; ?>
<?php
// -----
// Add multiple customers via uploaded .csv/.txt form rendering.
//
if ($action == 'add_multiple') {
    echo $infoDivContents;
}
?>
            <?php echo zen_draw_form('customers', FILENAME_ADD_CUSTOMERS, '', 'post', 'enctype="multipart/form-data" class="form-horizontal"') .
                       zen_hide_session_id() .
                       zen_draw_hidden_field('action', 'add_multiple'); ?>
            <h2 class="row formAreaTitle"><?php echo CUSTOMERS_BULK_UPLOAD; ?></h2>
            <div class="formArea">
                <div class="form-group">
                    <?php echo zen_draw_label(CUSTOMERS_FILE_IMPORT, 'bulk_upload', 'class="col-sm-3 control-label"'); ?>
                    <div class="col-sm-9"><?php echo zen_draw_file_field('bulk_upload', true, 'class="form-control" id="bulk_upload"'); ?></div>
                </div>
                <div class="row">
                    <div class="pull-left noprint">
                        <a href="<?php echo HTTP_SERVER . DIR_WS_CATALOG; ?>add_customers_formatting_csv.html" rel="noopener" target="_blank" class="btn btn-sm btn-default btn-help" role="button" title="<?php echo TEXT_HELP_CSV_FORMAT; ?>" aria-label="<?php echo TEXT_HELP_CSV_FORMAT; ?>">
                            <i class="fa fa-question fa-lg" aria-hidden="true"></i>
                        </a>
                    </div>
                    <div class="pull-right">
                        <button name="add_customers_in_bulk" type="submit" class="btn btn-primary"><?php echo IMAGE_UPLOAD; ?></button>
                    </div>
                </div>
            </div>
            <?php echo '</form>'; ?>
            <div class="formArea">
<?php
if ($printFormMissingFile !== '') {
?>
                <div class="row"><div class="alert alert-warning"><?php echo sprintf(ERROR_PRINT_FORM_MISSING, $printFormMissingFile); ?></div></div>
<?php
}
?>
                <div class="row">
                    <div class="col-md-6">
                        <a href="<?php echo zen_href_link(FILENAME_ADD_CUSTOMERS, 'action=download_csv_template'); ?>" class="btn btn-sm btn-default"><?php echo DOWNLOAD_CSV_TEMPLATE; ?></a>
                    </div>
                </div>
                <div class="row" style="margin-top:10px">
                    <div class="col-md-6 col-print-standard" style="margin-bottom:10px">
                        <a href="<?php echo zen_href_link(FILENAME_ADD_CUSTOMERS, 'action=print_form'); ?>" target="_blank" class="btn btn-sm btn-default"><?php echo PRINT_SIGNUP_FORM; ?></a>
                    </div>
<?php
if ($wholesaleEnabled) {
?>
                    <div class="col-md-6 col-print-wholesale">
                        <a href="<?php echo zen_href_link(FILENAME_ADD_CUSTOMERS, 'action=print_form&wholesale=1'); ?>" target="_blank" class="btn btn-sm btn-default"><?php echo PRINT_SIGNUP_FORM_WHOLESALE; ?></a>
                    </div>
<?php
}
?>
                </div>
            </div>
<?php
// -----
// Resend-email form rendering.
//
if ($action == 'resend_email') {
    echo $infoDivContents;
}
?>
            <?php echo zen_draw_form('resend', FILENAME_ADD_CUSTOMERS, '', 'post', 'enctype="multipart/form-data" class="form-horizontal"') .
                  zen_hide_session_id() .
                  zen_draw_hidden_field('action', 'resend_email'); ?>
            <h2 class="row formAreaTitle"><?php echo RESEND_WELCOME_EMAIL; ?></h2>
            <div class="formArea">
                <div class="form-group">
                    <?php echo zen_draw_label(TEXT_CHOOSE_CUSTOMER, 'resend_id', 'class="col-sm-4 control-label"'); ?>
                    <div class="col-sm-8 col-md-6"><?php echo zen_draw_pull_down_menu('resend_id', $acfa->createCustomerDropdown(), $resendID, 'id="resend_id"'); ?></div>
                </div>
                <div class="form-group">
                    <?php echo zen_draw_label(TEXT_RESET_PASSWORD, 'reset_pw', 'class="col-sm-4 control-label"'); ?>
                    <div class="col-sm-8 col-md-6">
                        <?php // -----
                        // zen_draw_checkbox_field()'s parameters argument turned out not to be
                        // raw HTML attributes at all - a passed id="reset_pw"/class="..." was
                        // silently dropped from the rendered output (confirmed via the live
                        // page source), leaving the label's for="reset_pw" with nothing to
                        // match. Writing the checkbox directly sidesteps needing to know what
                        // that argument actually does.
                        //
                        // No class here - form-control is meant for block-level, full-width
                        // text inputs/selects (~34px tall), and applying it to a checkbox made
                        // it render oversized, like a button rather than a checkbox. ?>
                        <input type="checkbox" name="reset_pw" id="reset_pw" value="1"<?php echo (isset($_POST['reset_pw'])) ? ' checked' : ''; ?>>

                    </div>
                </div>
                <div class="row text-right">
                    <button name="resend" type="submit" class="btn btn-primary"><?php echo BUTTON_RESEND; ?></button>
                </div>
            </div>
            <?php echo '</form>'; ?>
<?php
// -----
// Delete-abandoned-signups form rendering.
//
if ($action == 'delete_abandoned') {
    echo $infoDivContents;
}
?>
            <?php echo zen_draw_form('delete_abandoned', FILENAME_ADD_CUSTOMERS, '', 'post', 'class="form-horizontal"') .
                  zen_hide_session_id() .
                  zen_draw_hidden_field('action', 'delete_abandoned'); ?>
            <h2 class="row formAreaTitle"><?php echo DELETE_ABANDONED_SIGNUPS; ?></h2>
            <div class="formArea">
                <p class="help-block"><?php echo HELPTEXT_DELETE_ABANDONED; ?></p>
                <div class="form-group">
                    <?php echo zen_draw_label(TEXT_DELETE_BEFORE_DATE, 'delete_before_date', 'class="col-sm-4 control-label"'); ?>
                    <div class="col-sm-8 col-md-6"><?php echo zen_draw_input_field('delete_before_date', '', 'class="form-control" id="delete_before_date"', true, 'date'); ?></div>
                </div>
                <div class="row text-right">
                    <button name="delete_abandoned_btn" type="submit" class="btn btn-danger" onclick="return confirm('<?php echo addslashes(TEXT_DELETE_ABANDONED_CONFIRM); ?>');"><?php echo BUTTON_DELETE_ABANDONED; ?></button>
                </div>
            </div>
            <?php echo '</form>'; ?>
        </div>

        <div class="col-md-8 col-main-right">
<?php
// -----
// Add single-customer form rendering.
//
if ($action === 'add_single') {
    echo $infoDivContents;
}
?>
            <?php echo zen_draw_form('customers_1', FILENAME_ADD_CUSTOMERS, '', 'post', 'class="form-horizontal"') .
                       zen_hide_session_id() .
                       zen_draw_hidden_field('action', 'add_single'); ?>

            <h2 class="row formAreaTitle"><?php echo CUSTOMERS_SINGLE_ENTRY; ?></h2>
            <div class="formArea">
                <h3 class="row formAreaTitle"><?php echo CATEGORY_PERSONAL; ?></h3>
                <div class="formArea">
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_FIRST_NAME, 'customers_firstname', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_firstname', htmlspecialchars($cInfo->customers_firstname, ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_CUSTOMERS, 'customers_firstname', 50) . ' class="form-control" id="customers_firstname"', true); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_LAST_NAME, 'customers_lastname', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_lastname', htmlspecialchars($cInfo->customers_lastname, ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_CUSTOMERS, 'customers_lastname', 50) . ' class="form-control" id="customers_lastname"', true); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_EMAIL_ADDRESS, 'customers_email_address', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_email_address', htmlspecialchars($cInfo->customers_email_address, ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_CUSTOMERS, 'customers_email_address', 50) . ' class="form-control" id="customers_email_address"', true); ?>
                        </div>
                    </div>
                </div>
                <h3 class="row formAreaTitle"><?php echo CATEGORY_CONTACT; ?></h3>
                <div class="formArea">
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_TELEPHONE_NUMBER, 'customers_telephone', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_telephone', htmlspecialchars($cInfo->customers_telephone, ENT_COMPAT, CHARSET, TRUE), zen_set_field_length(TABLE_CUSTOMERS, 'customers_telephone', 15) . ' class="form-control" id="customers_telephone"', false); ?>
                        </div>
                    </div>
                </div>

                <h3 class="row formAreaTitle"><?php echo CATEGORY_OPTIONS; ?></h3>
                <div class="formArea">
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_DISCOUNT_PRICING_GROUP, 'customers_group_pricing', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
<?php
$group_array_query = $db->Execute(
    "SELECT group_id, group_name, group_percentage
      FROM " . TABLE_GROUP_PRICING
);
$group_array[] = array('id' => 0, 'text' => TEXT_NONE);
foreach ($group_array_query as $item) {
    $group_array[] = ['id' => $item['group_id'], 'text' => $item['group_name'] . '&nbsp;' . $item['group_percentage'] . '%'];
}
echo zen_draw_pull_down_menu('customers_group_pricing', $group_array, $cInfo->customers_group_pricing, 'class="form-control" id="customers_group_pricing"');
?>
                        </div>
                    </div>
<?php
if ($wholesaleEnabled) {
?>
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_WHOLESALE, 'customers_whole', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_whole', $cInfo->customers_whole, 'class="form-control" inputmode="numeric" pattern="[0-9]*" maxlength="4" id="customers_whole"', false, 'text'); ?>
                            <span class="help-block"><?php echo HELPTEXT_WHOLESALE; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo zen_draw_label(ENTRY_TAX_NUMBER, 'customers_tax_number', 'class="col-sm-3 control-label"'); ?>
                        <div class="col-sm-9 col-md-6">
                            <?php echo zen_draw_input_field('customers_tax_number', htmlspecialchars($cInfo->customers_tax_number, ENT_COMPAT, CHARSET, TRUE), 'maxlength="32" class="form-control" id="customers_tax_number"'); ?>
                        </div>
                    </div>
<?php
}
?>
                </div>
                <div class="row"><?php echo zen_draw_separator('pixel_trans.gif', '1', '10'); ?></div>
                <div class="row text-right">
                    <button name="insert" type="submit" class="btn btn-primary"><?php echo IMAGE_INSERT; ?></button>
                </div>
            </div>
            <?php echo '</form>'; ?>
        </div>
    </div>
<?php
require DIR_WS_INCLUDES . 'footer.php';
?>
</body>
</html>
<?php
require DIR_WS_INCLUDES . 'application_bottom.php';
